def main():
	info('Pump line after aux tank input')
	open('19')
	open('9')
	sleep(10)
	gosub('CryoWaitPump')
	sleep(60)
	close('16')
	open('15')
	close('32')
	close('34')
	sleep(60)
	set_cryo('freeze')
	sleep(5)
	close('14')
