def main():
	info('Pump line after furnace input')
	open('50')
	open('57')
	open('9')
	sleep(10)
	gosub('CryoWaitPump')
	sleep(60)
	close('16')
	open('15')
	sleep(60)
	set_cryo('freeze')
	sleep(5)
	close('14')
